# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Game.create(name:"Chess", genre:"strategy", description:"Chess is a two-player strategy board game played on a chessboard, a checkered gameboard with 64 squares arranged in an 8×8 grid.[1] The game is played by millions of people worldwide. Each player begins with 16 pieces: one king, one queen, two rooks, two knights, two bishops, and eight pawns. Each of the six piece types moves differently, with the most powerful being the queen and the least powerful the pawn. The objective is to checkmate[note 1] the opponent's king by placing it under an inescapable threat of capture. To this end, a player's pieces are used to attack and capture the opponent's pieces, while supporting each other. In addition to checkmate, the game can be won by voluntary resignation of the opponent, which typically occurs when too much material is lost or checkmate appears inevitable. There are also several ways a game can end in a draw.", num_players:"2")
Game.create(name:"Dungeon & Dragons", genre:"RPG", description:"Dungeons & Dragons is a structured yet open-ended role-playing game. It is normally played indoors with the participants seated around a tabletop. Typically, each player controls only a single character, which represents an individual in a fictional setting. When working together as a group, these player characters (PCs) are often described as a 'party' of adventurers, with each member often having their own area of specialty which contributes to the success of the whole. During the course of play, each player directs the actions of their character and their interactions with other characters in the game. This activity is performed through the verbal impersonation of the characters by the players, while employing a variety of social and other useful cognitive skills, such as logic, basic mathematics and imagination. A game often continues over a series of meetings to complete a single adventure, and longer into a series of related gaming adventures, called a 'campaign'.", num_players:"up to 13")
Game.create(name:"Mafia", genre:"deception", description:"In its simplest form, Mafia is played by two teams: the mafia and the innocents. Live games require a moderator who does not participate as a player, and identities are assigned by handing out cards. At the start of the game, every mafioso is given the identities of their teammates, whereas the innocents only receive the number of mafioso in the game, and do not know which players are mafia and which are innocents.", num_players:"6")
User.create(name:"Kevin Mercado", email:"kevin@email.com", password_digest:"password", phone:"7083360936", bio:"sometimes lucky", game_id:3, twitter_handle:"@KmercBeastmode", facebook_link:"https://www.facebook.com/KMERCBEASTMODE")
User.create(name:"Haruka Amami", email:"haruka@email.com", password_digest:"password", phone:"3127650403", bio:"best girl", game_id:3, twitter_handle:"", facebook_link:"")
User.create(name:"Jeremy Wang", email:"jeremy@email.com", password_digest:"password", phone:"3123720477", bio:"this guy is toast", game_id:1, twitter_handle:"https://twitter.com/disguisedtoast", facebook_link:"https://www.facebook.com/disguisedtoast")
Event.create(name:"Mafia Night in the City", datetime:"April 22nd, 2018 - 7PM-10PM", address:"1950 N Campbell", user_id:1, game_id:"3",num_players:"13")